[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Pycubed-Mini"
authors = [{name = "Aleksei Seletskiy", email = "lesha.seletskiy@gmail.com"}]
dynamic = ["version", "description"]